/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.iescavanilles;

/**
 *
 * @author vicen
 */
public class JFramePrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JFramePrincipal.class.getName());

    /**
     * Creates new form JFramePrincipal
     */
    public JFramePrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GrupoDeBotones = new javax.swing.ButtonGroup();
        lblHolaMundo = new javax.swing.JLabel();
        tbtnEncender = new javax.swing.JToggleButton();
        cbPlayStation = new javax.swing.JCheckBox();
        cbXbox = new javax.swing.JCheckBox();
        cbWii = new javax.swing.JCheckBox();
        rbtnFerrari = new javax.swing.JRadioButton();
        rbtnMustang = new javax.swing.JRadioButton();
        rbtnCamaro = new javax.swing.JRadioButton();
        CambiarTexto = new javax.swing.JButton();
        lblEncendido = new javax.swing.JLabel();
        btnMostrarConsola = new javax.swing.JButton();
        lblConsolaSel = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        lblCoche = new javax.swing.JLabel();
        comboxCoches = new javax.swing.JComboBox<>();
        btnComBoxCoche = new javax.swing.JButton();
        lblComBoxCoche = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        tfNombre = new javax.swing.JTextField();
        lblConsultaNombre = new javax.swing.JLabel();
        btnConsultaNombre = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblHolaMundo.setText("Hola Mundo con Swing");

        tbtnEncender.setText("Encender");
        tbtnEncender.addActionListener(this::tbtnEncenderActionPerformed);

        cbPlayStation.setText("PlayStation");
        cbPlayStation.addActionListener(this::cbPlayStationActionPerformed);

        cbXbox.setText("Xbox");

        cbWii.setText("Wii");

        GrupoDeBotones.add(rbtnFerrari);
        rbtnFerrari.setText("Ferrari");
        rbtnFerrari.addActionListener(this::rbtnFerrariActionPerformed);

        GrupoDeBotones.add(rbtnMustang);
        rbtnMustang.setText("Mustang");
        rbtnMustang.addActionListener(this::rbtnMustangActionPerformed);

        GrupoDeBotones.add(rbtnCamaro);
        rbtnCamaro.setText("Camaro");

        CambiarTexto.setText("CambiarTexto");
        CambiarTexto.addActionListener(this::CambiarTextoActionPerformed);

        lblEncendido.setText(tbtnEncender.getText());

        btnMostrarConsola.setText("Mostrar");
        btnMostrarConsola.addActionListener(this::btnMostrarConsolaActionPerformed);

        lblConsolaSel.setText("Selecciona una consola");
        lblConsolaSel.setToolTipText("Selecciona una consola");

        jButton1.setText("Mostrar");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        lblCoche.setText("Selecciona un coche");

        comboxCoches.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ferrari", "Ford", "Mustang", "BMW" }));
        comboxCoches.addActionListener(this::comboxCochesActionPerformed);

        btnComBoxCoche.setText("Mostrar");
        btnComBoxCoche.addActionListener(this::btnComBoxCocheActionPerformed);

        lblComBoxCoche.setText("Selecciona un coche");

        lblNombre.setText("Nombre:");

        tfNombre.addActionListener(this::tfNombreActionPerformed);

        lblConsultaNombre.setText("Tu nombre es:");

        btnConsultaNombre.setText("Consulta");
        btnConsultaNombre.addActionListener(this::btnConsultaNombreActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbPlayStation)
                            .addComponent(cbXbox)
                            .addComponent(cbWii, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnMostrarConsola)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblConsolaSel, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblHolaMundo)
                                .addGap(18, 18, 18)
                                .addComponent(CambiarTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbtnCamaro)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblEncendido, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(tbtnEncender, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblCoche, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(rbtnMustang)
                            .addComponent(rbtnFerrari)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(comboxCoches, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnComBoxCoche)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblComBoxCoche, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(39, 39, 39))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblConsultaNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnConsultaNombre)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHolaMundo)
                    .addComponent(CambiarTexto)
                    .addComponent(lblEncendido)
                    .addComponent(tbtnEncender))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbPlayStation)
                    .addComponent(rbtnFerrari))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbXbox)
                    .addComponent(rbtnMustang))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbWii)
                    .addComponent(rbtnCamaro))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(btnMostrarConsola)
                    .addComponent(lblCoche)
                    .addComponent(lblConsolaSel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboxCoches, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnComBoxCoche)
                    .addComponent(lblComBoxCoche))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre)
                    .addComponent(tfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConsultaNombre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblConsultaNombre)
                .addContainerGap(97, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbtnEncenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbtnEncenderActionPerformed
        if(tbtnEncender.isSelected()){
            lblEncendido.setText("Encendido");
            tbtnEncender.setText("Apagar");
        }else{
            lblEncendido.setText("Apagado");
            tbtnEncender.setText("Encender");
        }
    }//GEN-LAST:event_tbtnEncenderActionPerformed

    private void cbPlayStationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPlayStationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbPlayStationActionPerformed

    private void rbtnFerrariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnFerrariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnFerrariActionPerformed

    private void CambiarTextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CambiarTextoActionPerformed
        lblHolaMundo.setText("HolaHolaHolaHolaHolaHola");
    }//GEN-LAST:event_CambiarTextoActionPerformed

    private void btnMostrarConsolaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarConsolaActionPerformed
        if(cbPlayStation.isSelected()){
            lblConsolaSel.setText("Consola seleccionada: " + cbPlayStation.getText());
        }else if(cbXbox.isSelected()){
            lblConsolaSel.setText("Consola seleccionada: " + cbXbox.getText());
        }else if(cbWii.isSelected()){
            lblConsolaSel.setText("Consola seleccionada: " + cbWii.getText());
        }
    }//GEN-LAST:event_btnMostrarConsolaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(rbtnFerrari.isSelected()){
            lblCoche.setText("Coche Seleccionado: " + rbtnFerrari.getText());
        }else if(rbtnMustang.isSelected()){
            lblCoche.setText("Coche seleccionada: " + rbtnMustang.getText());
        }else if(cbWii.isSelected()){
            lblCoche.setText("Consola seleccionada: " + rbtnCamaro.getText());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void rbtnMustangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnMustangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnMustangActionPerformed

    private void comboxCochesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboxCochesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboxCochesActionPerformed

    private void btnComBoxCocheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComBoxCocheActionPerformed
        // TODO add your handling code here:
        
        String coche;
        int selectedItem;
        
        selectedItem = comboxCoches.getSelectedIndex();
        coche = comboxCoches.getItemAt(selectedItem);
        
        lblComBoxCoche.setText("Coche seleccionado: " + coche);
    }//GEN-LAST:event_btnComBoxCocheActionPerformed

    private void tfNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNombreActionPerformed

    private void btnConsultaNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultaNombreActionPerformed
        // TODO add your handling code here:
        String nombre = tfNombre.getText();
        lblNombre.setText("Tu nombre es: " + nombre);
    }//GEN-LAST:event_btnConsultaNombreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new JFramePrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CambiarTexto;
    private javax.swing.ButtonGroup GrupoDeBotones;
    private javax.swing.JButton btnComBoxCoche;
    private javax.swing.JButton btnConsultaNombre;
    private javax.swing.JButton btnMostrarConsola;
    private javax.swing.JCheckBox cbPlayStation;
    private javax.swing.JCheckBox cbWii;
    private javax.swing.JCheckBox cbXbox;
    private javax.swing.JComboBox<String> comboxCoches;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel lblCoche;
    private javax.swing.JLabel lblComBoxCoche;
    private javax.swing.JLabel lblConsolaSel;
    private javax.swing.JLabel lblConsultaNombre;
    private javax.swing.JLabel lblEncendido;
    private javax.swing.JLabel lblHolaMundo;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JRadioButton rbtnCamaro;
    private javax.swing.JRadioButton rbtnFerrari;
    private javax.swing.JRadioButton rbtnMustang;
    private javax.swing.JToggleButton tbtnEncender;
    private javax.swing.JTextField tfNombre;
    // End of variables declaration//GEN-END:variables
}
